basePath: /api/v1
host: localhost:3001
info:
  contact: {}
  description: 后端基础架构api文档
  title: 后端基础架构api文档
  version: "1.0"
paths:
  /user:
    get:
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: size
        required: true
        type: integer
      - description: 用户名
        in: query
        name: name
        type: string
      responses: {}
      summary: 请求用户列表
      tags:
      - 用户
swagger: "2.0"
