basePath: /api/v1
definitions:
  dto.CreateUserDto:
    properties:
      email:
        type: string
      isRoot:
        type: boolean
      nickname:
        type: string
      password:
        type: string
      username:
        description: BasicDto
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: 后端基础架构api文档
  title: 后端基础架构api文档
  version: "1.0"
paths:
  /user:
    get:
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: size
        required: true
        type: integer
      - description: 用户名
        in: query
        name: name
        type: string
      responses: {}
      summary: 请求用户列表
      tags:
      - 用户
    post:
      parameters:
      - description: 用户信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserDto'
      responses: {}
      summary: 创建用户
      tags:
      - 用户
  /user/{id}:
    delete:
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 删除用户
      tags:
      - 用户
    get:
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: 通过id 查询用户
      tags:
      - 用户
swagger: "2.0"
